# Generated by Django 3.1 on 2021-01-27 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_changelog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChangeLog',
            new_name='Patch',
        ),
    ]
